// <auto-generated />
using System;

using ChangeGuard.Infrastructure.Persistence;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChangeGuard.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ChangeGuardDbContext))]
[Migration("20260831120000_CompleteChangeRequestWorkflow")]
partial class CompleteChangeRequestWorkflow
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity(
            "ChangeGuard.Domain.ChangeRequests.ChangeRequest",
            b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<bool>("HasQaEvidence")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bit")
                    .HasDefaultValue(false);

                b.Property<bool>("HasRollbackPlan")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bit")
                    .HasDefaultValue(false);

                b.Property<string>("Priority")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("QaEvidenceNotes")
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<string>("ReferenceNumber")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("RollbackPlan")
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(40)
                    .HasColumnType("nvarchar(40)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTimeOffset>("UpdatedUtc")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("ReferenceNumber")
                    .IsUnique()
                    .HasDatabaseName("UX_ChangeRequests_ReferenceNumber");

                b.ToTable("ChangeRequests", (string)null);
            });

        modelBuilder.Entity(
            "ChangeGuard.Domain.ChangeRequests.ChangeRequestAuditEntry",
            b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Action")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("nvarchar(80)");

                b.Property<string>("Actor")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<Guid>("ChangeRequestId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Comment")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<string>("FromStatus")
                    .HasMaxLength(40)
                    .HasColumnType("nvarchar(40)");

                b.Property<DateTimeOffset>("OccurredUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("ToStatus")
                    .IsRequired()
                    .HasMaxLength(40)
                    .HasColumnType("nvarchar(40)");

                b.HasKey("Id");

                b.HasIndex("ChangeRequestId", "OccurredUtc")
                    .HasDatabaseName("IX_ChangeRequestAuditEntries_Request_OccurredUtc");

                b.ToTable("ChangeRequestAuditEntries", (string)null);
            });

        modelBuilder.Entity(
            "ChangeGuard.Domain.ChangeRequests.ChangeRequestAuditEntry",
            b =>
            {
                b.HasOne(
                        "ChangeGuard.Domain.ChangeRequests.ChangeRequest",
                        null)
                    .WithMany()
                    .HasForeignKey("ChangeRequestId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
